
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ projects

GET http://localhost:8000/api/v1/project/
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/project/1
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/project/1/record
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/project/1/record/lasts
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/project/1/user/1
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/project/1/user/1/new
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/project
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
    "name": "Project X",
    "keys": []
}

GET http://localhost:8000/api/v1/project/1
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/project/1/record
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "user_id": 1,
  "record": { "step": 1, "mood": 65 }
}

PUT http://localhost:8000/api/v1/project/3
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
    "name": "Project X",
    "keys": ["step"]
}

# }}}
